#if UNITY_EDITOR
using System.Diagnostics;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.PackageManager;

namespace Dennokoworks
{
    [InitializeOnLoad]
    public static class DennokoExVRCLVDetector
    {
        const string VRCLVFolder  = "Packages/red.sim.lightvolumes";
        const string VRCLVInclude = "Packages/red.sim.lightvolumes/Shaders/LightVolumes.cginc";

        // ~ suffix: Unity ignores this file entirely (no .meta, excluded from Export Package and VPM).
        const string InjectAsset  = "Assets/dennokoworks/DennokoEx/Shaders/DennokoEx_VRCLV_Inject.cginc~";
        // Bridge is a normal Unity asset; reimporting it triggers transitive shader recompile.
        const string BridgeAsset  = "Assets/dennokoworks/DennokoEx/Shaders/DennokoEx_VRCLV_Bridge.cginc";

        static DennokoExVRCLVDetector()
        {
            Events.registeredPackages += _ => EditorApplication.delayCall += Regenerate;
            SetupGitSkipWorktree();
            Regenerate();
        }

        [MenuItem("Window/DennokoEx/Regenerate VRCLV Bridge")]
        public static void Regenerate()
        {
            bool available = AssetDatabase.IsValidFolder(VRCLVFolder);
            string content = available ? ContentAvailable() : ContentUnavailable();

            string fullPath = Path.GetFullPath(InjectAsset);
            if (File.Exists(fullPath) && File.ReadAllText(fullPath, Encoding.UTF8) == content)
                return;

            File.WriteAllText(fullPath, content, Encoding.UTF8);
            // Reimport bridge (normal asset) so Unity recompiles all transitively dependent shaders.
            EditorApplication.delayCall += () =>
                AssetDatabase.ImportAsset(BridgeAsset, ImportAssetOptions.ForceUpdate);
        }

        // Resets inject file to safe default (VRCLV=0) before distributing the package.
        // Run this before exporting/releasing the package.
        [MenuItem("Window/DennokoEx/Prepare for Export (Reset VRCLV Bridge)")]
        public static void PrepareForExport()
        {
            string fullPath = Path.GetFullPath(InjectAsset);
            string safe = ContentUnavailable();
            if (File.Exists(fullPath) && File.ReadAllText(fullPath, Encoding.UTF8) == safe)
            {
                EditorUtility.DisplayDialog("DennokoEx", "Inject file is already in safe state. No changes made.", "OK");
                return;
            }
            File.WriteAllText(fullPath, safe, Encoding.UTF8);
            EditorApplication.delayCall += () =>
                AssetDatabase.ImportAsset(BridgeAsset, ImportAssetOptions.ForceUpdate);
            EditorUtility.DisplayDialog("DennokoEx", "DennokoEx_VRCLV_Inject.cginc~ has been reset to safe default.\nYou can now export the package.", "OK");
        }

        // Prevent accidental commits of the VRCLV=1 inject file in git-based VPM packages.
        static void SetupGitSkipWorktree()
        {
            try
            {
                string projectRoot = Path.GetFullPath(Path.Combine(UnityEngine.Application.dataPath, ".."));
                var psi = new ProcessStartInfo("git", $"update-index --skip-worktree {InjectAsset}")
                {
                    WorkingDirectory = projectRoot,
                    UseShellExecute = false,
                    CreateNoWindow  = true,
                };
                Process.Start(psi);
            }
            catch { } // Silently ignore if git is unavailable or this is not a git repo
        }

        static string ContentAvailable() =>
            "// Auto-generated by DennokoExVRCLVDetector.cs — do not edit manually.\n" +
            "// VRCLV detected. To regenerate: Window > DennokoEx > Regenerate VRCLV Bridge\n" +
            "#ifndef DNKW_VRCLV_INJECT_INCLUDED\n" +
            "#define DNKW_VRCLV_INJECT_INCLUDED\n" +
            "#include \"" + VRCLVInclude + "\"\n" +
            "#define DNKW_VRCLV_INJECTED 1\n" +
            "#endif\n";

        static string ContentUnavailable() =>
            "// Auto-generated by DennokoExVRCLVDetector.cs — do not edit manually.\n" +
            "// VRCLV not detected. To regenerate: Window > DennokoEx > Regenerate VRCLV Bridge\n";
    }
}
#endif
