#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Dennokoworks
{
    // Persists packed masks as ordinary PNG assets and keeps each material's _CustomMaskPacked pointing
    // at the one matching its current mask slots.
    //
    // Model:
    //   * The individual mask slots are the source of truth; the packed PNG is derived data.
    //   * Files are content-addressed and immutable: the name is a hash of the inputs (slot texture
    //     GUIDs + their import dependency hashes + packer version). Changing a slot or a source image
    //     yields a different file, so an existing file is never overwritten under another material —
    //     duplicated materials, Undo and shared inputs all stay consistent by construction.
    //   * EnsureAll is idempotent: when the assigned texture already is the expected file it writes
    //     nothing. Every trigger (inspector, asset changes, build) just calls it, and repeated calls
    //     converge after at most one write, so no loop guard or retry state is needed.
    //   * Compression, mipmaps and streaming come from the TextureImporter (see
    //     DennokoExPackedMaskWatcher), identically in the editor preview and in uploads.
    public static class DennokoExPackedMaskStore
    {
        public const string Folder = "Assets/DennokoEx_Generated/PackedMasks";

        public static bool IsGeneratedPath(string path)
            => !string.IsNullOrEmpty(path)
               && path.Replace('\\', '/').StartsWith(Folder + "/", System.StringComparison.OrdinalIgnoreCase);

        // Makes every DennokoEx material in `materials` reference the packed mask matching its slots
        // (or nothing, when all slots are empty). Other materials are ignored.
        //   persist: save changed .mat assets right away, so the reference survives reloads/reimports.
        //            Builds pass false to avoid saving (and reimporting) assets mid-build.
        //   rebake:  regenerate the files even if they exist (manual repair).
        // Returns false if any material could not be brought up to date; the reason is logged and the
        // material keeps its previous packed texture.
        public static bool EnsureAll(IEnumerable<Material> materials, bool persist, bool rebake = false)
        {
            var plans = new List<KeyValuePair<Material, string>>();
            var seen = new HashSet<Material>();
            var written = new HashSet<string>();
            bool ok = true;
            bool editing = false;

            // Pass 1: decide each material's file and create missing ones. Imports are batched.
            try
            {
                foreach (var m in materials)
                {
                    if (!DennokoExMaskPacker.HasPackedSlot(m) || !seen.Add(m)) continue;
                    if (!DennokoExMaskPacker.NeedsPacking(m))
                    {
                        plans.Add(new KeyValuePair<Material, string>(m, null));
                        continue;
                    }

                    byte[] png = null;
                    string key = InputKey(m);
                    if (key == null)
                    {
                        // A slot holds a texture that is not a saved asset (e.g. generated by another tool
                        // during the build), so the inputs cannot be identified. Bake, and name the file
                        // by its contents instead, which still de-duplicates repeated builds.
                        png = DennokoExMaskPacker.BakePng(m);
                        if (png == null) { ok = false; LogFailure(m); continue; }
                        key = "o" + Hash128.Compute(png);
                    }

                    string path = Folder + "/" + key + ".png";
                    if ((rebake || !File.Exists(path)) && written.Add(path))
                    {
                        if (png == null) png = DennokoExMaskPacker.BakePng(m);
                        if (png == null) { ok = false; LogFailure(m); continue; }
                        if (!editing)
                        {
                            EnsureFolder();
                            AssetDatabase.StartAssetEditing();
                            editing = true;
                        }
                        File.WriteAllBytes(path, png);
                        AssetDatabase.ImportAsset(path);
                    }
                    plans.Add(new KeyValuePair<Material, string>(m, path));
                }
            }
            finally
            {
                if (editing) AssetDatabase.StopAssetEditing();
            }

            // Pass 2: assign. Only materials whose reference actually changes are touched.
            foreach (var plan in plans)
            {
                var m = plan.Key;
                Texture2D tex = null;
                if (plan.Value != null)
                {
                    tex = AssetDatabase.LoadAssetAtPath<Texture2D>(plan.Value);
                    if (tex == null)
                    {
                        AssetDatabase.ImportAsset(plan.Value, ImportAssetOptions.ForceSynchronousImport);
                        tex = AssetDatabase.LoadAssetAtPath<Texture2D>(plan.Value);
                    }
                    if (tex == null)
                    {
                        ok = false;
                        Debug.LogError($"[DennokoEx] Packed mask '{plan.Value}' for material '{m.name}' could not be loaded.", m);
                        continue;
                    }
                }

                if (m.GetTexture(DennokoExMaskPacker.PackedProp) == tex) continue;
                m.SetTexture(DennokoExMaskPacker.PackedProp, tex);
                EditorUtility.SetDirty(m);
                if (persist && CanSave(m)) AssetDatabase.SaveAssetIfDirty(m);
            }
            return ok;
        }

        // Hash of everything the baked pixels depend on, or null if a slot texture is not a saved asset.
        // Deliberately not the material's own dependency hash: that includes the packed texture itself.
        static string InputKey(Material m)
        {
            var sb = new StringBuilder("v").Append(DennokoExMaskPacker.Version).Append(';');
            for (int i = 0; i < DennokoExMaskPacker.SourceProps.Length; i++)
            {
                var t = DennokoExMaskPacker.GetSource(m, i);
                if (t == null) { sb.Append("_;"); continue; }
                if (!AssetDatabase.TryGetGUIDAndLocalFileIdentifier(t, out string guid, out long localId)) return null;
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(path)) return null;
                // The dependency hash covers the source file and its import settings (sRGB, max size...).
                sb.Append(guid).Append(':').Append(localId).Append(':')
                  .Append(AssetDatabase.GetAssetDependencyHash(path)).Append(';');
            }
            return "i" + Hash128.Compute(sb.ToString());
        }

        // Only standalone, writable .mat files are saved. Materials embedded in models, in immutable
        // packages, or created in memory still get the reference, but only for this session/build.
        static bool CanSave(Material m)
            => EditorUtility.IsPersistent(m)
               && AssetDatabase.GetAssetPath(m).EndsWith(".mat", System.StringComparison.OrdinalIgnoreCase)
               && AssetDatabase.IsOpenForEdit(m);

        static void EnsureFolder()
        {
            string current = null;
            foreach (var part in Folder.Split('/'))
            {
                string next = current == null ? part : current + "/" + part;
                if (current != null && !AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, part);
                current = next;
            }
        }

        static void LogFailure(Material m)
            => Debug.LogError($"[DennokoEx] Could not pack the masks of material '{m.name}'. Its packed mask was left unchanged.", m);

        // ------------------------------------------------------------------------------------------
        //  Project-wide maintenance
        // ------------------------------------------------------------------------------------------

        // Distinct asset paths containing at least one material. FindAssets returns GUIDs per file, and a
        // file (model, .asset) may hold several materials, so callers must use LoadMaterialsAtPath.
        public static List<string> FindMaterialContainerPaths()
        {
            var paths = new List<string>();
            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets("t:Material"))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!string.IsNullOrEmpty(path) && seen.Add(path)) paths.Add(path);
            }
            return paths;
        }

        // Every DennokoEx material stored in the file, main asset or sub-asset.
        public static List<Material> LoadMaterialsAtPath(string path)
        {
            var result = new List<Material>();
            if (string.IsNullOrEmpty(path)) return result;
            foreach (var o in AssetDatabase.LoadAllAssetsAtPath(path))
                if (o is Material m && DennokoExMaskPacker.HasPackedSlot(m)) result.Add(m);
            return result;
        }

        [MenuItem("Window/DennokoEx/Packed Masks/Update All Materials")]
        static void UpdateAllMaterials()
        {
            var materials = new List<Material>();
            var paths = FindMaterialContainerPaths();
            try
            {
                for (int i = 0; i < paths.Count; i++)
                {
                    if (EditorUtility.DisplayCancelableProgressBar("DennokoEx", paths[i], (float)i / paths.Count)) return;
                    materials.AddRange(LoadMaterialsAtPath(paths[i]));
                }
            }
            finally { EditorUtility.ClearProgressBar(); }

            bool ok = EnsureAll(materials, persist: true);
            Debug.Log($"[DennokoEx] Checked the packed masks of {materials.Count} material(s)" +
                      (ok ? "." : "; some failed, see the errors above."));
        }

        // Generated files are never deleted automatically: an older file may still be referenced by
        // an Undo step, an unsaved scene material or another project copy.
        [MenuItem("Window/DennokoEx/Packed Masks/Delete Unused Generated Masks")]
        static void DeleteUnused()
        {
            if (!AssetDatabase.IsValidFolder(Folder)) return;

            var used = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets("t:Material"))
                foreach (var dep in AssetDatabase.GetDependencies(AssetDatabase.GUIDToAssetPath(guid), false))
                    if (IsGeneratedPath(dep)) used.Add(dep);

            var unused = new List<string>();
            foreach (var guid in AssetDatabase.FindAssets("t:Texture2D", new[] { Folder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!used.Contains(path)) unused.Add(path);
            }

            if (unused.Count == 0)
            {
                EditorUtility.DisplayDialog("DennokoEx", "No unused packed masks were found.", "OK");
                return;
            }
            if (!EditorUtility.DisplayDialog("DennokoEx",
                    $"Delete {unused.Count} packed mask file(s) not referenced by any saved material?\n" +
                    "Unsaved materials that still use them will regenerate them when edited or built.",
                    "Delete", "Cancel"))
                return;

            var failed = new List<string>();
            AssetDatabase.DeleteAssets(unused.ToArray(), failed);
            foreach (var f in failed) Debug.LogWarning($"[DennokoEx] Could not delete '{f}'.");
        }
    }
}
#endif
