#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Dennokoworks
{
    // Persists packed masks as ordinary PNG assets and keeps each material's _CustomMaskPacked pointing
    // at the one matching its current mask slots.
    //
    // Model:
    //   * The individual mask slots are the source of truth; the packed PNG is derived data.
    //   * Files are content-addressed and immutable: the name is a hash of the inputs (slot texture
    //     GUIDs + their import dependency hashes + packer version). Changing a slot or a source image
    //     yields a different file, so an existing file is never overwritten under another material —
    //     duplicated materials, Undo and shared inputs all stay consistent by construction.
    //   * EnsureAll is idempotent: when the assigned texture already is the expected file it writes
    //     nothing. Every trigger (inspector, asset changes, build) just calls it, and repeated calls
    //     converge after at most one write, so no loop guard or retry state is needed.
    //   * Compression, mipmaps and streaming come from the TextureImporter, identically in the editor
    //     preview and in uploads. The settings are written to the generated files' own importers
    //     (EnsureImportSettings), NOT by an AssetPostprocessor.OnPreprocessTexture: registering a
    //     texture preprocessor changes the import dependency of every texture, so installing or
    //     updating the extension would reimport all textures of the project.
    public static class DennokoExPackedMaskStore
    {
        public const string Folder = "Assets/DennokoEx_Generated/PackedMasks";

        // GUID of Shaders/lts.lilcontainer; its folder holds every shader DennokoEx materials can use.
        const string ShaderAssetGuid = "7d1b6c3fca9cc82499ca6d8b767fabb6";

        public static bool IsGeneratedPath(string path)
            => !string.IsNullOrEmpty(path)
               && path.Replace('\\', '/').StartsWith(Folder + "/", System.StringComparison.OrdinalIgnoreCase);

        // Makes every DennokoEx material in `materials` reference the packed mask matching its slots
        // (or nothing, when all slots are empty). Other materials are ignored.
        //   persist: save changed .mat assets right away, so the reference survives reloads/reimports.
        //            Builds pass false to avoid saving (and reimporting) assets mid-build.
        //   rebake:  regenerate the files even if they exist (manual repair).
        // Returns false if any material could not be brought up to date; the reason is logged and the
        // material keeps its previous packed texture.
        public static bool EnsureAll(IEnumerable<Material> materials, bool persist, bool rebake = false)
        {
            var plans = new List<KeyValuePair<Material, string>>();
            var seen = new HashSet<Material>();
            var written = new HashSet<string>();
            bool ok = true;
            bool editing = false;

            // Pass 1: decide each material's file and create missing ones. Imports are batched.
            try
            {
                foreach (var m in materials)
                {
                    if (!DennokoExMaskPacker.HasPackedSlot(m) || !seen.Add(m)) continue;
                    if (!DennokoExMaskPacker.NeedsPacking(m))
                    {
                        plans.Add(new KeyValuePair<Material, string>(m, null));
                        continue;
                    }

                    byte[] png = null;
                    string key = InputKey(m);
                    if (key == null)
                    {
                        // A slot holds a texture that is not a saved asset (e.g. generated by another tool
                        // during the build), so the inputs cannot be identified. Bake, and name the file
                        // by its contents instead, which still de-duplicates repeated builds.
                        png = DennokoExMaskPacker.BakePng(m);
                        if (png == null) { ok = false; LogFailure(m); continue; }
                        key = "o" + Hash128.Compute(png);
                    }

                    string path = Folder + "/" + key + ".png";
                    if ((rebake || !File.Exists(path)) && written.Add(path))
                    {
                        if (png == null) png = DennokoExMaskPacker.BakePng(m);
                        if (png == null) { ok = false; LogFailure(m); continue; }
                        if (!editing)
                        {
                            EnsureFolder();
                            AssetDatabase.StartAssetEditing();
                            editing = true;
                        }
                        File.WriteAllBytes(path, png);
                        AssetDatabase.ImportAsset(path);
                    }
                    plans.Add(new KeyValuePair<Material, string>(m, path));
                }
            }
            finally
            {
                if (editing) AssetDatabase.StopAssetEditing();
            }

            var paths = new HashSet<string>();
            foreach (var plan in plans)
                if (plan.Value != null) paths.Add(plan.Value);
            EnsureImportSettings(paths);

            // Pass 2: assign. Only materials whose reference actually changes are touched.
            foreach (var plan in plans)
            {
                var m = plan.Key;
                Texture2D tex = null;
                if (plan.Value != null)
                {
                    tex = AssetDatabase.LoadAssetAtPath<Texture2D>(plan.Value);
                    if (tex == null)
                    {
                        AssetDatabase.ImportAsset(plan.Value, ImportAssetOptions.ForceSynchronousImport);
                        tex = AssetDatabase.LoadAssetAtPath<Texture2D>(plan.Value);
                    }
                    if (tex == null)
                    {
                        ok = false;
                        Debug.LogError($"[DennokoEx] Packed mask '{plan.Value}' for material '{m.name}' could not be loaded.", m);
                        continue;
                    }
                }

                if (m.GetTexture(DennokoExMaskPacker.PackedProp) == tex) continue;
                m.SetTexture(DennokoExMaskPacker.PackedProp, tex);
                EditorUtility.SetDirty(m);
                if (persist && CanSave(m)) AssetDatabase.SaveAssetIfDirty(m);
            }
            return ok;
        }

        // Hash of everything the baked pixels depend on, or null if a slot texture is not a saved asset.
        // Deliberately not the material's own dependency hash: that includes the packed texture itself.
        static string InputKey(Material m)
        {
            var sb = new StringBuilder("v").Append(DennokoExMaskPacker.Version).Append(';');
            for (int i = 0; i < DennokoExMaskPacker.SourceProps.Length; i++)
            {
                var t = DennokoExMaskPacker.GetSource(m, i);
                if (t == null) { sb.Append("_;"); continue; }
                if (!AssetDatabase.TryGetGUIDAndLocalFileIdentifier(t, out string guid, out long localId)) return null;
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(path)) return null;
                // The dependency hash covers the source file and its import settings (sRGB, max size...).
                sb.Append(guid).Append(':').Append(localId).Append(':')
                  .Append(AssetDatabase.GetAssetDependencyHash(path)).Append(';');
            }
            return "i" + Hash128.Compute(sb.ToString());
        }

        // Only standalone, writable .mat files are saved. Materials embedded in models, in immutable
        // packages, or created in memory still get the reference, but only for this session/build.
        static bool CanSave(Material m)
            => EditorUtility.IsPersistent(m)
               && AssetDatabase.GetAssetPath(m).EndsWith(".mat", System.StringComparison.OrdinalIgnoreCase)
               && AssetDatabase.IsOpenForEdit(m);

        static void EnsureFolder()
        {
            string current = null;
            foreach (var part in Folder.Split('/'))
            {
                string next = current == null ? part : current + "/" + part;
                if (current != null && !AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, part);
                current = next;
            }
        }

        static void LogFailure(Material m)
            => Debug.LogError($"[DennokoEx] Could not pack the masks of material '{m.name}'. Its packed mask was left unchanged.", m);

        // ------------------------------------------------------------------------------------------
        //  Import settings of the generated files
        // ------------------------------------------------------------------------------------------

        const int ImportMaxSize = 2048;

        static readonly (string platform, TextureImporterFormat format)[] PlatformFormats =
        {
            ("Standalone", TextureImporterFormat.BC7),
            ("Android", TextureImporterFormat.ASTC_6x6),
            ("iPhone", TextureImporterFormat.ASTC_6x6),
        };

        // Reimports only the files whose importer differs, so it is a no-op once the settings are in
        // the .meta. A new file is imported once with defaults first and once more here.
        static void EnsureImportSettings(IEnumerable<string> paths)
        {
            bool editing = false;
            try
            {
                foreach (var path in paths)
                {
                    if (!(AssetImporter.GetAtPath(path) is TextureImporter ti) || !ApplyImportSettings(ti)) continue;
                    if (!editing)
                    {
                        AssetDatabase.StartAssetEditing();
                        editing = true;
                    }
                    ti.SaveAndReimport();
                }
            }
            finally
            {
                if (editing) AssetDatabase.StopAssetEditing();
            }
        }

        // The packed channels are four unrelated linear masks:
        //   * sRGB off and alpha taken as-is, so values match what the individual slots produced.
        //   * BC7 on PC rather than DXT5: DXT5 fits RGB to one line per 4x4 block, bleeding the
        //     independent R/G/B masks into each other. ASTC on mobile, which has no BC7.
        //   * Mipmaps + streaming for VRChat's texture memory budget; no CPU copy.
        // Returns true if anything had to be changed.
        static bool ApplyImportSettings(TextureImporter ti)
        {
            bool changed = false;
            void Set<T>(T current, T target, System.Action<T> set)
            {
                if (EqualityComparer<T>.Default.Equals(current, target)) return;
                set(target);
                changed = true;
            }

            Set(ti.textureType, TextureImporterType.Default, v => ti.textureType = v);
            Set(ti.textureShape, TextureImporterShape.Texture2D, v => ti.textureShape = v);
            Set(ti.sRGBTexture, false, v => ti.sRGBTexture = v);
            Set(ti.alphaSource, TextureImporterAlphaSource.FromInput, v => ti.alphaSource = v);
            Set(ti.alphaIsTransparency, false, v => ti.alphaIsTransparency = v);
            Set(ti.npotScale, TextureImporterNPOTScale.None, v => ti.npotScale = v);
            Set(ti.mipmapEnabled, true, v => ti.mipmapEnabled = v);
            Set(ti.streamingMipmaps, true, v => ti.streamingMipmaps = v);
            Set(ti.isReadable, false, v => ti.isReadable = v);
            Set(ti.wrapMode, TextureWrapMode.Repeat, v => ti.wrapMode = v);
            Set(ti.filterMode, FilterMode.Bilinear, v => ti.filterMode = v);
            Set(ti.maxTextureSize, ImportMaxSize, v => ti.maxTextureSize = v);
            Set(ti.textureCompression, TextureImporterCompression.CompressedHQ, v => ti.textureCompression = v);

            foreach (var (platform, format) in PlatformFormats)
            {
                var s = ti.GetPlatformTextureSettings(platform);
                if (s.overridden && s.format == format && s.maxTextureSize == ImportMaxSize
                    && s.compressionQuality == (int)TextureCompressionQuality.Normal)
                    continue;
                s.overridden = true;
                s.format = format;
                s.maxTextureSize = ImportMaxSize;
                s.compressionQuality = (int)TextureCompressionQuality.Normal;
                ti.SetPlatformTextureSettings(s);
                changed = true;
            }
            return changed;
        }

        // ------------------------------------------------------------------------------------------
        //  Project-wide maintenance
        // ------------------------------------------------------------------------------------------

        // Distinct asset paths containing at least one material. FindAssets returns GUIDs per file, and a
        // file (model, .asset) may hold several materials, so callers must use LoadMaterialsAtPath.
        public static List<string> FindMaterialContainerPaths()
        {
            var paths = new List<string>();
            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets("t:Material"))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!string.IsNullOrEmpty(path) && seen.Add(path)) paths.Add(path);
            }
            return paths;
        }

        // Folder of the DennokoEx shaders ("…/Shaders/"), or null if they cannot be located.
        static string ShaderFolder()
        {
            string path = AssetDatabase.GUIDToAssetPath(ShaderAssetGuid);
            if (string.IsNullOrEmpty(path)) path = AssetDatabase.GetAssetPath(Shader.Find("dennokoworks/DennokoEx"));
            return string.IsNullOrEmpty(path) ? null : Path.GetDirectoryName(path).Replace('\\', '/') + "/";
        }

        // Whether a file whose direct dependencies are `dependencies` may hold a DennokoEx material.
        // Reads the dependency database only, so it is far cheaper than LoadAllAssetsAtPath on models
        // and large .asset files. Without a located shader folder nothing can be ruled out.
        public static bool UsesDennokoExShader(string[] dependencies)
        {
            string folder = ShaderFolder();
            if (folder == null) return true;
            foreach (var dep in dependencies)
                if (dep.StartsWith(folder, System.StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        public static bool UsesDennokoExShader(string path)
            => UsesDennokoExShader(AssetDatabase.GetDependencies(path, false));

        // Every DennokoEx material stored in the file, main asset or sub-asset.
        public static List<Material> LoadMaterialsAtPath(string path)
        {
            var result = new List<Material>();
            if (string.IsNullOrEmpty(path)) return result;
            foreach (var o in AssetDatabase.LoadAllAssetsAtPath(path))
                if (o is Material m && DennokoExMaskPacker.HasPackedSlot(m)) result.Add(m);
            return result;
        }

        [MenuItem("Window/DennokoEx/Packed Masks/Update All Materials")]
        static void UpdateAllMaterials()
        {
            var materials = new List<Material>();
            var paths = FindMaterialContainerPaths();
            try
            {
                for (int i = 0; i < paths.Count; i++)
                {
                    if (EditorUtility.DisplayCancelableProgressBar("DennokoEx", paths[i], (float)i / paths.Count)) return;
                    if (UsesDennokoExShader(paths[i])) materials.AddRange(LoadMaterialsAtPath(paths[i]));
                }
            }
            finally { EditorUtility.ClearProgressBar(); }

            bool ok = EnsureAll(materials, persist: true);
            Debug.Log($"[DennokoEx] Checked the packed masks of {materials.Count} material(s)" +
                      (ok ? "." : "; some failed, see the errors above."));
        }

        // Generated files are never deleted automatically: an older file may still be referenced by
        // an Undo step, an unsaved scene material or another project copy.
        [MenuItem("Window/DennokoEx/Packed Masks/Delete Unused Generated Masks")]
        static void DeleteUnused()
        {
            if (!AssetDatabase.IsValidFolder(Folder)) return;

            var used = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets("t:Material"))
                foreach (var dep in AssetDatabase.GetDependencies(AssetDatabase.GUIDToAssetPath(guid), false))
                    if (IsGeneratedPath(dep)) used.Add(dep);

            var unused = new List<string>();
            foreach (var guid in AssetDatabase.FindAssets("t:Texture2D", new[] { Folder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!used.Contains(path)) unused.Add(path);
            }

            if (unused.Count == 0)
            {
                EditorUtility.DisplayDialog("DennokoEx", "No unused packed masks were found.", "OK");
                return;
            }
            if (!EditorUtility.DisplayDialog("DennokoEx",
                    $"Delete {unused.Count} packed mask file(s) not referenced by any saved material?\n" +
                    "Unsaved materials that still use them will regenerate them when edited or built.",
                    "Delete", "Cancel"))
                return;

            var failed = new List<string>();
            AssetDatabase.DeleteAssets(unused.ToArray(), failed);
            foreach (var f in failed) Debug.LogWarning($"[DennokoEx] Could not delete '{f}'.");
        }
    }
}
#endif
