#if UNITY_EDITOR
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.PackageManager;

namespace Dennokoworks
{
    [InitializeOnLoad]
    public static class DennokoExVRCLVDetector
    {
        const string PackageName  = "red.sim.lightvolumes";
        const string BridgeAsset  = "Assets/dennokoworks/DennokoEx/Shaders/Shaders/DennokoEx_VRCLV_Bridge.cginc";
        const string VRCLVInclude = "Packages/red.sim.lightvolumes/Shaders/LightVolumes.cginc";

        static DennokoExVRCLVDetector()
        {
            Events.registeredPackages  += _ => EditorApplication.delayCall += Regenerate;
            Events.unregisteredPackages += _ => EditorApplication.delayCall += Regenerate;
            Regenerate();
        }

        [MenuItem("Window/DennokoEx/Regenerate VRCLV Bridge")]
        public static void Regenerate()
        {
            bool available = UnityEditor.PackageManager.PackageInfo.FindForPackageName(PackageName) != null;
            string content = available ? ContentAvailable() : ContentUnavailable();

            string fullPath = Path.GetFullPath(BridgeAsset);
            if (File.Exists(fullPath) && File.ReadAllText(fullPath, Encoding.UTF8) == content)
                return;

            File.WriteAllText(fullPath, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(BridgeAsset, ImportAssetOptions.ForceUpdate);
        }

        static string ContentAvailable() =>
            "// Auto-generated by DennokoExVRCLVDetector.cs — do not edit manually.\n" +
            "// To regenerate: Window > DennokoEx > Regenerate VRCLV Bridge\n" +
            "#ifndef DNKW_VRCLV_BRIDGE_INCLUDED\n" +
            "#define DNKW_VRCLV_BRIDGE_INCLUDED\n" +
            "#include \"" + VRCLVInclude + "\"\n" +
            "#define DNKW_VRCLV_AVAILABLE 1\n" +
            "#endif\n";

        static string ContentUnavailable() =>
            "// Auto-generated by DennokoExVRCLVDetector.cs — do not edit manually.\n" +
            "// To regenerate: Window > DennokoEx > Regenerate VRCLV Bridge\n" +
            "#ifndef DNKW_VRCLV_BRIDGE_INCLUDED\n" +
            "#define DNKW_VRCLV_BRIDGE_INCLUDED\n" +
            "#define DNKW_VRCLV_AVAILABLE 0\n" +
            "#endif\n";
    }
}
#endif
