//----------------------------------------------------------------------------------------------------------------------
// DennokoEx custom.hlsl - lilToon 2.x Extended Shader
// Features: 2nd Reflection (Specular) / 2nd Rim / 3rd Normal Map / Decal
//----------------------------------------------------------------------------------------------------------------------

// VRC Light Volumes optional integration.
// DennokoEx_VRCLV_Bridge.cginc is auto-generated by DennokoExVRCLVDetector.cs.
// Regenerate manually: Window > DennokoEx > Regenerate VRCLV Bridge
#include "UnityCG.cginc"
#include "DennokoEx_VRCLV_Bridge.cginc"

// CBUFFER Variable Declarations
#define LIL_CUSTOM_PROPERTIES \
    float4 _CustomRefl2ndColor; \
    float  _CustomRefl2ndStrength; \
    float  _CustomRefl2ndSmoothness; \
    float  _CustomRefl2ndAnisotropic; \
    float  _CustomRefl2ndAnisoPrimaryShift; \
    float4 _CustomRefl2ndAnisoSecondaryColor; \
    float  _CustomRefl2ndAnisoSecondaryStrength; \
    float  _CustomRefl2ndAnisoSecondaryShift; \
    float  _CustomRefl2ndShadowAttenuation; \
    float  _CustomRefl2ndNormalStrength; \
    float  _CustomRefl2ndEnabled; \
    float4 _CustomRim2ndColor; \
    float  _CustomRim2ndPower; \
    float  _CustomRim2ndStrength; \
    float  _CustomRim2ndBlendMode; \
    float  _CustomRim2ndShadowAttenuation; \
    float  _CustomRim2ndNormalStrength; \
    float  _CustomRim2ndEnabled; \
    float4 _CustomNormal3rdTex_ST; \
    float  _CustomNormal3rdStrength; \
    float  _CustomNormal3rdEnabled; \
    float  _CustomRefl2ndLVColorStrength; \
    float  _CustomRefl2ndMainColorStrength; \
    float  _CustomRefl2ndBlur; \
    float4 _CustomRefl2ndMaskTex_ST; \
    float  _CustomRim2ndMainColorStrength; \
    float  _CustomRim2ndBlur; \
    float4 _CustomMain4thColor; \
    float4 _CustomMain4thTex_ST; \
    float  _CustomMain4thTex_UVMode; \
    float  _CustomMain4thTexBlendMode; \
    float  _CustomMain4thTexAlphaMode; \
    float  _CustomMain4thShadowDisable; \
    float  _CustomMain4thEnabled; \
    float4 _CustomDecalColor; \
    float  _CustomDecalAlpha; \
    float  _CustomDecalBlendMode; \
    float  _CustomDecalShadowDisable; \
    float  _CustomDecalEnabled; \
    float  _CustomDecalPosX; \
    float  _CustomDecalPosY; \
    float  _CustomDecalSizeX; \
    float  _CustomDecalSizeY; \
    float  _CustomDecalAngle; \
    float4 _CustomDecalMatcapColor; \
    float  _CustomDecalMatcapAlpha; \
    float  _CustomDecalMatcapBlendMode; \
    float  _CustomDecalMatcapShadowDisable; \
    float  _CustomDecalMatcapEnableLighting; \
    float  _CustomDecalMatcapEnabled; \
    float4 _CustomDecalNormalTex_ST; \
    float  _CustomDecalNormalStrength; \
    float  _CustomDecalNormalEnabled;

// Texture Declarations.
// Two limits apply: 16 SAMPLERS (ps_4_0) -> solved by sharing sampler_linear_repeat;
// and 64 TEXTURE PARAMETERS per shader -> the all-features-on build (PostprocessBuild)
// pushed the transparent pass to 65 and broke it. To stay well under 64 the four
// single-channel masks are packed into one RGBA texture (_CustomMaskPacked):
//   R = Reflection 2nd mask   G = Rim 2nd mask   B = Normal 3rd mask   A = Main Color 4th mask
// Each channel is still sampled with its own UV below, so no feature is lost;
// only the declared texture COUNT drops. The individual mask slots remain in the
// property block for authoring and are baked into _CustomMaskPacked at build time.
#define LIL_CUSTOM_TEXTURES \
    TEXTURE2D(_CustomMaskPacked); \
    TEXTURE2D(_CustomNormal3rdTex); \
    TEXTURE2D(_CustomDecalTex); \
    TEXTURE2D(_CustomDecalMaskTex); \
    TEXTURE2D(_CustomDecalMatcapTex); \
    TEXTURE2D(_CustomDecalNormalTex); \
    TEXTURE2D(_CustomMain4thTex);

// Add vertex copy
#define LIL_CUSTOM_VERT_COPY

// Decal mipmap gradient scale.
// The decal UV magnifies the mesh UV by tiling (= 1/size), so its screen-space
// derivatives are tiling-times larger than the mesh UV. The GPU then picks a mip
// level ~log2(tiling) levels too coarse, making the decal go blurry fast.
// Scaling the gradients by this factor weakens the mipmap response: 1.0 = default
// automatic mip behavior, 0.1 = ~1/10 strength (sharper, current setting).
#define DNKW_DECAL_MIP_GRAD_SCALE 0.1

// Blend helper for decal: mode 0=Replace, 1=Add, 2=Screen, 3=Multiply
// alpha is pre-multiplied into overlay for Add/Screen modes, used as lerp weight for Replace/Multiply
float3 DNKW_DecalBlend(float3 base, float3 overlay, float alpha, float mode)
{
    float3 mReplace  = lerp(base, overlay, alpha);
    float3 mAdd      = base + overlay * alpha;
    float3 mScreen   = 1.0 - (1.0 - base) * (1.0 - overlay * alpha);
    float3 mMultiply = lerp(base, base * overlay, alpha);
    float3 r = mReplace;
    r = lerp(r, mAdd,      step(0.5, mode));
    r = lerp(r, mScreen,   step(1.5, mode));
    r = lerp(r, mMultiply, step(2.5, mode));
    return r;
}

// Matcap lighting correction — mirrors lilToon's lilGetMatCap (_MatCapEnableLighting).
// Without this the decal matcap renders at constant full brightness and "floats" against
// the surrounding environment. fd.lightColor is the scene/light color of the current pass.
// Implemented as a function (not inline in the macro) so the LIL_PASS_FORWARDADD branch can
// use #if — preprocessor directives are illegal inside an object-like macro body.
// ForwardBase: lerp toward lightColor by enableLighting (matches lilToon base pass).
// ForwardAdd : multiply by the additive light color so extra lights don't add the matcap at
//   full brightness; skipped for Multiply blend (mode 3), same as lilToon's `_MatCapBlendMode < 3`.
float3 DNKW_MatcapLighting(float3 mc, float3 lightColor, float enableLighting, float blendMode)
{
    #if !defined(LIL_PASS_FORWARDADD)
        return lerp(mc, mc * lightColor, enableLighting);
    #else
        return (blendMode < 3) ? mc * lightColor * enableLighting : mc;
    #endif
}

// OVERRIDE_NORMAL_2ND - Normal Map 2nd preserving UVMode and blend
#define OVERRIDE_NORMAL_2ND \
    if(_UseBump2ndMap) \
    { \
        float2 _n2UV    = fd.uv0; \
        if(_Bump2ndMap_UVMode == 1) _n2UV = fd.uv1; \
        if(_Bump2ndMap_UVMode == 2) _n2UV = fd.uv2; \
        if(_Bump2ndMap_UVMode == 3) _n2UV = fd.uv3; \
        float4 _n2Tex   = LIL_SAMPLE_2D_ST(_Bump2ndMap, lil_sampler_linear_repeat, _n2UV); \
        float  _n2Scale = _Bump2ndScale * LIL_SAMPLE_2D_ST(_Bump2ndScaleMask, sampler_MainTex, fd.uvMain).r; \
        normalmap       = lilBlendNormal(normalmap, lilUnpackNormalScale(_n2Tex, _n2Scale)); \
    }

// BEFORE_RIMSHADE - Main Color 4th (stripped lilGetMain2nd).
//
// Placement: this hook fires AFTER lilToon's full Main 1st/2nd/3rd stack is assembled.
// lilToon blends the *un-lit* portion of Main 2nd/3rd (the `1 - EnableLighting` share) into
// fd.col only AFTER OVERRIDE_SHADOW (lil_pass_forward_normal.hlsl ~463-468), which is AFTER
// the older BEFORE_SHADOW hook. Compositing Main 4th at BEFORE_SHADOW therefore let those
// un-lit Main 2nd/3rd shares paint over Main 4th, hiding it whenever Main 2nd/3rd were used
// with EnableLighting < 1 (the common case). BEFORE_RIMSHADE runs after that blend, so Main 4th
// now reliably sits on top of the whole main-color stack, and still before the extension's own
// Reflection/Matcap/Rim layers.
//
// Lighting: to keep Main 4th lit exactly like the base main color (the original design intent),
// we work in albedo space. fd.albedo is the un-lit main color and (fd.col / fd.albedo) is the
// per-pixel lighting that was applied. We re-blend Main 4th into a new albedo and re-apply that
// lighting factor, which is exact for every lilBlendColor mode (lighting is a linear multiply).
// When Main 4th is disabled or its weight is 0 the new albedo equals fd.albedo, so fd.col is
// reconstructed unchanged (no-op).
//
// Omitted vs lilToon: MSDF / scroll / rotation / distance fade / dissolve.
// Kept: HDR color, texture (tiling/offset), UV channel select (0-3 + MatCap),
//       blend mode (lilBlendColor: 0=Normal,1=Add,2=Screen,3=Multiply),
//       alpha mode (0=Off,1=Replace,2=Multiply,3=Add,4=Subtract).
//
// Mask: the draw range is gated by an INDEPENDENT mask texture authored via the
// _CustomMain4thMaskTex slot and baked into _CustomMaskPacked.a (sampled at fd.uv0, mesh UV).
// The color blend weight is mask * _CustomMain4thColor.a; the main texture's own alpha is NOT
// used as the range. Default packed mask is white (.a = 1) so an unmasked layer covers fully.
//
// AlphaMode writes fd.col.a unconditionally: lilToon guards it with #if LIL_RENDER!=0, but #if
// is illegal inside a macro body. In opaque passes fd.col.a is unused at output and cutout
// clipping already happened earlier, so the write is harmless there. AlphaMode uses the pre-
// shadow weight (_m4a) so transparency is unaffected by Shadow Disable.
//
// Shadow Disable: fd.shadowmix is valid at this hook, so the color blend weight is faded out in
// shadow directly (only the color contribution, not the alpha-mode write above).
#define BEFORE_RIMSHADE \
    if (_CustomMain4thEnabled > 0.5) { \
        float2 _m4UV = fd.uv0; \
        if(_CustomMain4thTex_UVMode == 1) _m4UV = fd.uv1; \
        if(_CustomMain4thTex_UVMode == 2) _m4UV = fd.uv2; \
        if(_CustomMain4thTex_UVMode == 3) _m4UV = fd.uv3; \
        if(_CustomMain4thTex_UVMode == 4) _m4UV = fd.uvMat; \
        _m4UV = _m4UV * _CustomMain4thTex_ST.xy + _CustomMain4thTex_ST.zw; \
        float3 _m4rgb  = _CustomMain4thColor.rgb * LIL_SAMPLE_2D(_CustomMain4thTex, sampler_linear_repeat, _m4UV).rgb; \
        float  _m4Mask = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, fd.uv0).a; \
        float  _m4a    = _CustomMain4thColor.a * _m4Mask; \
        if(_CustomMain4thTexAlphaMode != 0) { \
            if(_CustomMain4thTexAlphaMode == 1) fd.col.a = _m4a; \
            if(_CustomMain4thTexAlphaMode == 2) fd.col.a = fd.col.a * _m4a; \
            if(_CustomMain4thTexAlphaMode == 3) fd.col.a = saturate(fd.col.a + _m4a); \
            if(_CustomMain4thTexAlphaMode == 4) fd.col.a = saturate(fd.col.a - _m4a); \
        } \
        float  _m4aRGB = _m4a * (1.0 - (1.0 - fd.shadowmix) * _CustomMain4thShadowDisable); \
        float3 _m4Light    = fd.col.rgb / max(fd.albedo, float3(1e-4, 1e-4, 1e-4)); \
        float3 _m4NewAlb   = lilBlendColor(fd.albedo, _m4rgb, _m4aRGB, _CustomMain4thTexBlendMode); \
        fd.col.rgb = _m4NewAlb * _m4Light; \
    }

// BEFORE_AUDIOLINK - 3rd Normal Map (composited after lilToon's normal pipeline)
// Uses lilUnpackNormalScale + lilBlendNormal, identical to lilToon's 1st->2nd blend,
// so strength scales the tangent xy without clamping (values >1 amplify, matching 1st/2nd)
// and additively layers on top of the existing 1st/2nd result.
// fd.reflectionN/matcapN/matcap2ndN/uvMat are updated here because they were set
// from the pre-3rd fd.N earlier in the pipeline (lil_pass_forward_normal.hlsl:314-316).
#define BEFORE_AUDIOLINK \
    if (_CustomNormal3rdEnabled > 0.5) { \
        float2 _n3UV    = fd.uv0 * _CustomNormal3rdTex_ST.xy + _CustomNormal3rdTex_ST.zw; \
        float  _n3Mask  = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, fd.uv0).b; \
        float4 _n3Raw   = LIL_SAMPLE_2D(_CustomNormal3rdTex, sampler_linear_repeat, _n3UV); \
        float3 _n3NTS   = lilUnpackNormalScale(_n3Raw, _CustomNormal3rdStrength * _n3Mask); \
        float3 _nCurTS  = mul(fd.TBN, fd.N); \
        float3 _nBlend  = lilBlendNormal(_nCurTS, _n3NTS); \
        fd.N            = normalize(mul(_nBlend, fd.TBN)); \
        fd.reflectionN  = fd.N; \
        fd.matcapN      = fd.N; \
        fd.matcap2ndN   = fd.N; \
        fd.uvMat        = mul(fd.cameraMatrix, fd.N).xy * 0.5 + 0.5; \
    } \
    /* Decal Normal Map: positioned/scaled/rotated by the decal placement (same algorithm as \
       BEFORE_MATCAP) and gated by the decal mask, then composited on top of fd.N exactly like \
       Normal 3rd. Done here (before reflection/lighting) so the decal's bumps actually react to \
       light. The placement math is recomputed here (not shared with BEFORE_MATCAP) so the block \
       stays self-contained across passes that may expand one hook but not the other. Strength is \
       authored -2..2: lilUnpackNormalScale handles negatives by flipping the tangent xy. */ \
    if (_CustomDecalNormalEnabled > 0.5) { \
        float2 _dnTiling = float2(1.0 / max(_CustomDecalSizeX, 0.0001), \
                                  1.0 / max(_CustomDecalSizeY, 0.0001)); \
        float2 _dnOffset = 0.5 - float2(_CustomDecalPosX, _CustomDecalPosY) * _dnTiling; \
        float  _dnAngle  = _CustomDecalAngle * 0.01745329252; \
        float  _dnSin, _dnCos; \
        sincos(_dnAngle, _dnSin, _dnCos); \
        float2 _dnC = fd.uv0 - 0.5; \
        float2 _dnRotUV = float2(_dnC.x * _dnCos - _dnC.y * _dnSin + 0.5, \
                                 _dnC.x * _dnSin + _dnC.y * _dnCos + 0.5); \
        float2 _dnDecalUV = _dnRotUV * _dnTiling + _dnOffset; \
        float2 _dnDdx = ddx(_dnDecalUV) * DNKW_DECAL_MIP_GRAD_SCALE; \
        float2 _dnDdy = ddy(_dnDecalUV) * DNKW_DECAL_MIP_GRAD_SCALE; \
        float  _dnInBounds = step(0.0, _dnDecalUV.x) * step(_dnDecalUV.x, 1.0) \
                           * step(0.0, _dnDecalUV.y) * step(_dnDecalUV.y, 1.0); \
        float  _dnMaskTex  = LIL_SAMPLE_2D_GRAD(_CustomDecalMaskTex, sampler_linear_repeat, _dnDecalUV, _dnDdx, _dnDdy).r; \
        float  _dnMask     = _dnInBounds * _dnMaskTex; \
        float2 _dnTexUV = _dnDecalUV * _CustomDecalNormalTex_ST.xy + _CustomDecalNormalTex_ST.zw; \
        float4 _dnRaw   = LIL_SAMPLE_2D_GRAD(_CustomDecalNormalTex, sampler_linear_repeat, _dnTexUV, _dnDdx * _CustomDecalNormalTex_ST.xy, _dnDdy * _CustomDecalNormalTex_ST.xy); \
        float3 _dnNTS   = lilUnpackNormalScale(_dnRaw, _CustomDecalNormalStrength * _dnMask); \
        float3 _dnCurTS = mul(fd.TBN, fd.N); \
        float3 _dnBlend = lilBlendNormal(_dnCurTS, _dnNTS); \
        fd.N            = normalize(mul(_dnBlend, fd.TBN)); \
        fd.reflectionN  = fd.N; \
        fd.matcapN      = fd.N; \
        fd.matcap2ndN   = fd.N; \
        fd.uvMat        = mul(fd.cameraMatrix, fd.N).xy * 0.5 + 0.5; \
    }

// BEFORE_REFLECTION - 2nd Reflection
// Isotropic (VRCLV): LightVolumeSpecular with LV color intensity control.
//   _CustomRefl2ndLVColorStrength: 0=LV輝度のみ(色無し), 1=LV色をフルで受け取る(デフォルト)
// Anisotropic: Kajiya-Kay (fd.L / fd.lightColor)
// 両パス共通: _CustomRefl2ndMainColorStrength でfd.albedoを最終出力に乗算
#if DNKW_VRCLV_AVAILABLE
#define BEFORE_REFLECTION \
    if (_CustomRefl2ndEnabled > 0.5) { \
        float2 _r2MaskUV = fd.uv0 * _CustomRefl2ndMaskTex_ST.xy + _CustomRefl2ndMaskTex_ST.zw; \
        float  _r2Mask   = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, _r2MaskUV).r; \
        float  _r2Shadow = lerp(1.0, fd.shadowmix, _CustomRefl2ndShadowAttenuation); \
        /* Blend reflection normal between geometry normal (origN) and the normal-mapped fd.N. */ \
        float3 _r2N = normalize(lerp(fd.origN, fd.N, _CustomRefl2ndNormalStrength)); \
        float3 _r2Out; \
        if (_CustomRefl2ndAnisotropic > 0.5) { \
            float  _r2HalfShin = exp2(_CustomRefl2ndSmoothness * 10.0 + 1.0) * 0.5; \
            float3 _r2H  = normalize(fd.L + fd.V); \
            float3 _r2T1 = normalize(fd.TBN[1] + _r2N * _CustomRefl2ndAnisoPrimaryShift); \
            float  _r2TH1   = dot(_r2T1, _r2H); \
            float  _r2Spec1 = smoothstep(-1.0, 0.0, _r2TH1) * pow(max(0.0, 1.0 - _r2TH1 * _r2TH1), _r2HalfShin); \
            float3 _r2T2 = normalize(fd.TBN[1] + _r2N * _CustomRefl2ndAnisoSecondaryShift); \
            float  _r2TH2   = dot(_r2T2, _r2H); \
            float  _r2Spec2 = smoothstep(-1.0, 0.0, _r2TH2) * pow(max(0.0, 1.0 - _r2TH2 * _r2TH2), _r2HalfShin * 0.5); \
            _r2Spec1 = lerp(step(0.5, _r2Spec1), _r2Spec1, _CustomRefl2ndBlur); \
            _r2Spec2 = lerp(step(0.5, _r2Spec2), _r2Spec2, _CustomRefl2ndBlur); \
            _r2Out = (_CustomRefl2ndColor.rgb * _r2Spec1 + _CustomRefl2ndAnisoSecondaryColor.rgb * _r2Spec2 * _CustomRefl2ndAnisoSecondaryStrength) * _CustomRefl2ndStrength * _r2Mask * _r2Shadow * fd.lightColor; \
        } else { \
            float3 _r2L0, _r2L1r, _r2L1g, _r2L1b; \
            LightVolumeSH(fd.positionWS, _r2L0, _r2L1r, _r2L1g, _r2L1b); \
            float3 _r2Spec = LightVolumeSpecular(float3(1.0, 1.0, 1.0), _CustomRefl2ndSmoothness, 1.0, _r2N, fd.V, _r2L0, _r2L1r, _r2L1g, _r2L1b); \
            float  _r2Lum  = dot(_r2Spec, float3(0.299, 0.587, 0.114)); \
            _r2Spec = lerp(float3(_r2Lum, _r2Lum, _r2Lum), _r2Spec, _CustomRefl2ndLVColorStrength); \
            /* Post-lerp luminance equals _r2Lum exactly (lerp(L,L,s)=L since luma weights sum to 1), so reuse it. */ \
            float  _r2Shaped  = lerp(step(0.5, _r2Lum), _r2Lum, _CustomRefl2ndBlur); \
            _r2Spec *= _r2Shaped / max(_r2Lum, 1e-5); \
            _r2Out  = _r2Spec * _CustomRefl2ndColor.rgb * _CustomRefl2ndStrength * _r2Mask; \
        } \
        fd.col.rgb += _r2Out * lerp(float3(1.0, 1.0, 1.0), fd.albedo, _CustomRefl2ndMainColorStrength); \
    }
#else
// VRCLV is unavailable only in extreme legacy environments where neither the
// red.sim package nor lilToon's bundled LightVolumes.cginc exists. Disable the
// reflection rather than fall back, so undefined LightVolume* calls never compile.
#define BEFORE_REFLECTION
#endif

// BEFORE_MATCAP - Decal UV setup + Decal base map
//
// Decal UV: same algorithm as lilCalcDecalUV.
//   Position (PosX/PosY) = decal center in UV space (0.5,0.5 = mesh UV center).
//   Size (SizeX/SizeY)   = fraction of UV space covered (1.0 = full UV width/height).
//   Tiling = 1/Size,  Offset = 0.5 - Pos * Tiling
//   Rotation is around mesh UV center (0.5,0.5), same as lilRotateUV.
//
// _CustomDecalMaskTex is sampled in DECAL UV SPACE (same transform as the decal texture).
//   This means the mask scales, moves, and rotates together with the decal.
//   It controls the precise shape of the effect within the placed decal area.
//   _dnkw_decalMask (bounds * maskTex.r) is stored for reuse in BEFORE_RIMLIGHT (Matcap).
//
// BlendMode: 0=Replace, 1=Add, 2=Screen, 3=Multiply.
#define BEFORE_MATCAP \
    /* Compute decal UV once; result shared with BEFORE_RIMLIGHT via _dnkw_decalMask. */ \
    float _dnkw_decalMask = 0.0; \
    float2 _dnkw_decalUV  = float2(0.0, 0.0); \
    float2 _dnkw_decalDdx = float2(0.0, 0.0); \
    float2 _dnkw_decalDdy = float2(0.0, 0.0); \
    if (_CustomDecalEnabled > 0.5 || _CustomDecalMatcapEnabled > 0.5) { \
        float2 _dTiling = float2(1.0 / max(_CustomDecalSizeX, 0.0001), \
                                 1.0 / max(_CustomDecalSizeY, 0.0001)); \
        float2 _dOffset = 0.5 - float2(_CustomDecalPosX, _CustomDecalPosY) * _dTiling; \
        float  _dAngle  = _CustomDecalAngle * 0.01745329252; \
        float  _dSin, _dCos; \
        sincos(_dAngle, _dSin, _dCos); \
        float2 _dC = fd.uv0 - 0.5; \
        float2 _dRotUV = float2(_dC.x * _dCos - _dC.y * _dSin + 0.5, \
                                _dC.x * _dSin + _dC.y * _dCos + 0.5); \
        _dnkw_decalUV  = _dRotUV * _dTiling + _dOffset; \
        /* Weaken the tiling-magnified mip response so the decal stays sharp. */ \
        _dnkw_decalDdx = ddx(_dnkw_decalUV) * DNKW_DECAL_MIP_GRAD_SCALE; \
        _dnkw_decalDdy = ddy(_dnkw_decalUV) * DNKW_DECAL_MIP_GRAD_SCALE; \
        float  _dInBounds = step(0.0, _dnkw_decalUV.x) * step(_dnkw_decalUV.x, 1.0) \
                          * step(0.0, _dnkw_decalUV.y) * step(_dnkw_decalUV.y, 1.0); \
        /* Mask sampled in decal UV space → scales/moves/rotates with the decal. */ \
        float  _dMaskTex  = LIL_SAMPLE_2D_GRAD(_CustomDecalMaskTex, sampler_linear_repeat, _dnkw_decalUV, _dnkw_decalDdx, _dnkw_decalDdy).r; \
        _dnkw_decalMask   = _dInBounds * _dMaskTex; \
    } \
    if (_CustomDecalEnabled > 0.5) { \
        float4 _dTex    = LIL_SAMPLE_2D_GRAD(_CustomDecalTex, sampler_linear_repeat, _dnkw_decalUV, _dnkw_decalDdx, _dnkw_decalDdy); \
        float  _dShadow = lerp(1.0, fd.shadowmix, _CustomDecalShadowDisable); \
        float  _dAlpha  = _dTex.a * _CustomDecalAlpha * _dnkw_decalMask * _dShadow; \
        float3 _dColor  = _dTex.rgb * _CustomDecalColor.rgb; \
        /* The base decal intentionally shares the matcap's _CustomDecalMatcapEnableLighting toggle. \
           The property name is kept (not renamed to a base-specific one) for backward compatibility \
           with materials authored against the previous implementation. Blend mode stays base-specific. */ \
        _dColor = DNKW_MatcapLighting(_dColor, fd.lightColor, _CustomDecalMatcapEnableLighting, _CustomDecalBlendMode); \
        fd.col.rgb = DNKW_DecalBlend(fd.col.rgb, _dColor, _dAlpha, _CustomDecalBlendMode); \
    }

// BEFORE_RIMLIGHT - Decal Matcap
// Matcap UV is view-space; the placement mask is _dnkw_decalMask computed in BEFORE_MATCAP.
// Both base and matcap share the same positioned/scaled/rotated decal mask.
#define BEFORE_RIMLIGHT \
    if (_CustomDecalMatcapEnabled > 0.5) { \
        /* Reuse lilToon's fd.uvMat (head-centered cameraMatrix, updated for Normal3rd above): \
           VR-correct (no per-eye stereo divergence) and saves a matrix multiply vs. UNITY_MATRIX_V. */ \
        float2 _mcUV     = fd.uvMat; \
        float4 _mcTex    = LIL_SAMPLE_2D(_CustomDecalMatcapTex, sampler_linear_repeat, _mcUV); \
        float  _mcShadow = lerp(1.0, fd.shadowmix, _CustomDecalMatcapShadowDisable); \
        float3 _mcColor  = _mcTex.rgb * _CustomDecalMatcapColor.rgb; \
        _mcColor = DNKW_MatcapLighting(_mcColor, fd.lightColor, _CustomDecalMatcapEnableLighting, _CustomDecalMatcapBlendMode); \
        float  _mcAlpha  = _mcTex.a * _CustomDecalMatcapAlpha * _dnkw_decalMask * _mcShadow; \
        fd.col.rgb = DNKW_DecalBlend(fd.col.rgb, _mcColor, _mcAlpha, _CustomDecalMatcapBlendMode); \
    }

// BEFORE_EMISSION_1ST - 2nd Rim
// (Main Color 4th, incl. its Shadow Disable, is handled at BEFORE_RIMSHADE.)
//
// 2nd Rim: applied after standard rim light. BlendMode: 0=RimLight(Add) / 1=RimShade(Multiply)
#define BEFORE_EMISSION_1ST \
    if (_CustomRim2ndEnabled > 0.5) { \
        float  _rim2Mask   = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, fd.uv0).g; \
        /* Blend rim normal between geometry normal (origN) and the normal-mapped fd.N. */ \
        float3 _rim2N      = normalize(lerp(fd.origN, fd.N, _CustomRim2ndNormalStrength)); \
        float  _rim2NdotV  = saturate(dot(_rim2N, fd.V)); \
        float  _rim2Val    = pow(1.0 - _rim2NdotV, _CustomRim2ndPower); \
        _rim2Val = lerp(step(0.5, _rim2Val), _rim2Val, _CustomRim2ndBlur); \
        float  _rim2Shadow = lerp(1.0, fd.shadowmix, _CustomRim2ndShadowAttenuation); \
        float  _rim2Amt    = _rim2Val * _CustomRim2ndStrength * _rim2Mask * _rim2Shadow; \
        float3 _rim2Color  = _CustomRim2ndColor.rgb * lerp(float3(1.0, 1.0, 1.0), fd.albedo, _CustomRim2ndMainColorStrength); \
        if (_CustomRim2ndBlendMode < 0.5) { \
            fd.col.rgb += _rim2Color * _rim2Amt; \
        } else { \
            fd.col.rgb = lerp(fd.col.rgb, fd.col.rgb * _rim2Color, _rim2Amt); \
        } \
    }

//----------------------------------------------------------------------------------------------------------------------
// Information about variables
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// Vertex shader inputs (appdata structure)
//
// Type     Name                    Description
// -------- ----------------------- --------------------------------------------------------------------
// float4   input.positionOS        POSITION
// float2   input.uv0               TEXCOORD0
// float2   input.uv1               TEXCOORD1
// float2   input.uv2               TEXCOORD2
// float2   input.uv3               TEXCOORD3
// float2   input.uv4               TEXCOORD4
// float2   input.uv5               TEXCOORD5
// float2   input.uv6               TEXCOORD6
// float2   input.uv7               TEXCOORD7
// float4   input.color             COLOR
// float3   input.normalOS          NORMAL
// float4   input.tangentOS         TANGENT
// uint     vertexID                SV_VertexID

//----------------------------------------------------------------------------------------------------------------------
// Vertex shader outputs or pixel shader inputs (v2f structure)
//
// The structure depends on the pass.
// Please check lil_pass_xx.hlsl for details.
//
// Type     Name                    Description
// -------- ----------------------- --------------------------------------------------------------------
// float4   output.positionCS       SV_POSITION
// float2   output.uv01             TEXCOORD0 TEXCOORD1
// float2   output.uv23             TEXCOORD2 TEXCOORD3
// float3   output.positionOS       object space position
// float3   output.positionWS       world space position
// float3   output.normalWS         world space normal
// float4   output.tangentWS        world space tangent

//----------------------------------------------------------------------------------------------------------------------
// Variables commonly used in the forward pass
//
// These are members of `lilFragData fd`
//
// Type     Name                    Description
// -------- ----------------------- --------------------------------------------------------------------
// float4   col                     lit color
// float3   albedo                  unlit color
// float3   emissionColor           color of emission
// -------- ----------------------- --------------------------------------------------------------------
// float3   lightColor              color of light
// float3   indLightColor           color of indirectional light
// float3   addLightColor           color of additional light
// float    attenuation             attenuation of light
// float3   invLighting             saturate((1.0 - lightColor) * sqrt(lightColor));
// -------- ----------------------- --------------------------------------------------------------------
// float2   uv0                     TEXCOORD0
// float2   uv1                     TEXCOORD1
// float2   uv2                     TEXCOORD2
// float2   uv3                     TEXCOORD3
// float2   uvMain                  Main UV
// float2   uvMat                   MatCap UV
// float2   uvRim                   Rim Light UV
// float2   uvPanorama              Panorama UV
// float2   uvScn                   Screen UV
// bool     isRightHand             input.tangentWS.w > 0.0;
// -------- ----------------------- --------------------------------------------------------------------
// float3   positionOS              object space position
// float3   positionWS              world space position
// float4   positionCS              clip space position
// float4   positionSS              screen space position
// float    depth                   distance from camera
// -------- ----------------------- --------------------------------------------------------------------
// float3x3 TBN                     tangent / bitangent / normal matrix
// float3   T                       tangent direction
// float3   B                       bitangent direction
// float3   N                       normal direction
// float3   V                       view direction
// float3   L                       light direction
// float3   origN                   normal direction without normal map
// float3   origL                   light direction without sh light
// float3   headV                   middle view direction of 2 cameras
// float3   reflectionN             normal direction for reflection
// float3   matcapN                 normal direction for reflection for MatCap
// float3   matcap2ndN              normal direction for reflection for MatCap 2nd
// float    facing                  VFACE
// -------- ----------------------- --------------------------------------------------------------------
// float    vl                      dot(viewDirection, lightDirection);
// float    hl                      dot(headDirection, lightDirection);
// float    ln                      dot(lightDirection, normalDirection);
// float    nv                      saturate(dot(normalDirection, viewDirection));
// float    nvabs                   abs(dot(normalDirection, viewDirection));
// -------- ----------------------- --------------------------------------------------------------------
// float4   triMask                 TriMask (for lite version)
// float3   parallaxViewDirection   mul(tbnWS, viewDirection);
// float2   parallaxOffset          parallaxViewDirection.xy / (parallaxViewDirection.z+0.5);
// float    anisotropy              strength of anisotropy
// float    smoothness              smoothness
// float    roughness               roughness
// float    perceptualRoughness     perceptual roughness
// float    shadowmix               this variable is 0 in the shadow area
// float    audioLinkValue          volume acquired by AudioLink
// -------- ----------------------- --------------------------------------------------------------------
// uint     renderingLayers         light layer of object (for URP / HDRP)
// uint     featureFlags            feature flags (for HDRP)
// uint2    tileIndex               tile index (for HDRP)
