//----------------------------------------------------------------------------------------------------------------------
// DennokoEx custom.hlsl - lilToon 2.x Extended Shader
// Features: 2nd Reflection (Specular) / 2nd Rim / 3rd Normal Map / Decal
//----------------------------------------------------------------------------------------------------------------------

// VRC Light Volumes optional integration.
// DennokoEx_VRCLV_Bridge.cginc is auto-generated by DennokoExVRCLVDetector.cs.
// Regenerate manually: Window > DennokoEx > Regenerate VRCLV Bridge
#include "UnityCG.cginc"
#include "DennokoEx_VRCLV_Bridge.cginc"

// CBUFFER Variable Declarations
#define LIL_CUSTOM_PROPERTIES \
    float4 _CustomRefl2ndColor; \
    float  _CustomRefl2ndStrength; \
    float  _CustomRefl2ndSmoothness; \
    float  _CustomRefl2ndAnisotropic; \
    float  _CustomRefl2ndAnisoPrimaryShift; \
    float4 _CustomRefl2ndAnisoSecondaryColor; \
    float  _CustomRefl2ndAnisoSecondaryStrength; \
    float  _CustomRefl2ndAnisoSecondaryShift; \
    float  _CustomRefl2ndShadowAttenuation; \
    float  _CustomRefl2ndEnabled; \
    float4 _CustomRim2ndColor; \
    float  _CustomRim2ndPower; \
    float  _CustomRim2ndStrength; \
    float  _CustomRim2ndBlendMode; \
    float  _CustomRim2ndShadowAttenuation; \
    float  _CustomRim2ndEnabled; \
    float4 _CustomNormal3rdTex_ST; \
    float  _CustomNormal3rdStrength; \
    float  _CustomNormal3rdEnabled; \
    float  _CustomRefl2ndLVColorStrength; \
    float  _CustomRefl2ndMainColorStrength; \
    float  _CustomRefl2ndBlur; \
    float4 _CustomRefl2ndMaskTex_ST; \
    float  _CustomRim2ndMainColorStrength; \
    float  _CustomRim2ndBlur; \
    float  _CustomMain2ndShadowDisable; \
    float  _CustomMain3rdShadowDisable; \
    float4 _CustomDecalColor; \
    float  _CustomDecalAlpha; \
    float  _CustomDecalBlendMode; \
    float  _CustomDecalShadowDisable; \
    float  _CustomDecalEnabled; \
    float  _CustomDecalPosX; \
    float  _CustomDecalPosY; \
    float  _CustomDecalSizeX; \
    float  _CustomDecalSizeY; \
    float  _CustomDecalAngle; \
    float4 _CustomDecalMatcapColor; \
    float  _CustomDecalMatcapAlpha; \
    float  _CustomDecalMatcapBlendMode; \
    float  _CustomDecalMatcapShadowDisable; \
    float  _CustomDecalMatcapEnabled;

// Texture Declarations.
// Two limits apply: 16 SAMPLERS (ps_4_0) -> solved by sharing sampler_linear_repeat;
// and 64 TEXTURE PARAMETERS per shader -> the all-features-on build (PostprocessBuild)
// pushed the transparent pass to 65 and broke it. To stay well under 64 the four
// single-channel masks are packed into one RGBA texture (_CustomMaskPacked):
//   R = Reflection 2nd mask   G = Rim 2nd mask   B = Normal 3rd mask   A = Normal 1st mask
// Each channel is still sampled with its own UV/tiling below, so no feature is lost;
// only the declared texture COUNT drops (8 -> 5). The individual mask slots remain in the
// property block for authoring and are baked into _CustomMaskPacked at build time.
#define LIL_CUSTOM_TEXTURES \
    TEXTURE2D(_CustomMaskPacked); \
    TEXTURE2D(_CustomNormal3rdTex); \
    TEXTURE2D(_CustomDecalTex); \
    TEXTURE2D(_CustomDecalMaskTex); \
    TEXTURE2D(_CustomDecalMatcapTex);

// Add vertex copy
#define LIL_CUSTOM_VERT_COPY

// Decal mipmap gradient scale.
// The decal UV magnifies the mesh UV by tiling (= 1/size), so its screen-space
// derivatives are tiling-times larger than the mesh UV. The GPU then picks a mip
// level ~log2(tiling) levels too coarse, making the decal go blurry fast.
// Scaling the gradients by this factor weakens the mipmap response: 1.0 = default
// automatic mip behavior, 0.1 = ~1/10 strength (sharper, current setting).
#define DNKW_DECAL_MIP_GRAD_SCALE 0.1

// Blend helper for decal: mode 0=Replace, 1=Add, 2=Screen, 3=Multiply
// alpha is pre-multiplied into overlay for Add/Screen modes, used as lerp weight for Replace/Multiply
float3 DNKW_DecalBlend(float3 base, float3 overlay, float alpha, float mode)
{
    float3 mReplace  = lerp(base, overlay, alpha);
    float3 mAdd      = base + overlay * alpha;
    float3 mScreen   = 1.0 - (1.0 - base) * (1.0 - overlay * alpha);
    float3 mMultiply = lerp(base, base * overlay, alpha);
    float3 r = mReplace;
    r = lerp(r, mAdd,      step(0.5, mode));
    r = lerp(r, mScreen,   step(1.5, mode));
    r = lerp(r, mMultiply, step(2.5, mode));
    return r;
}

// OVERRIDE_NORMAL_1ST - Normal Map 1st with per-pixel scale mask
// Scale mask = _CustomMaskPacked.a (authored via the _CustomBump1stMaskTex slot; default white = full strength)
#define OVERRIDE_NORMAL_1ST \
    if(_UseBumpMap) \
    { \
        float4 _n1Tex  = LIL_SAMPLE_2D_ST(_BumpMap, sampler_MainTex, fd.uvMain); \
        float  _n1Mask = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, fd.uvMain).a; \
        normalmap      = lilUnpackNormalScale(_n1Tex, _BumpScale * _n1Mask); \
    }

// OVERRIDE_NORMAL_2ND - Normal Map 2nd preserving UVMode and blend
#define OVERRIDE_NORMAL_2ND \
    if(_UseBump2ndMap) \
    { \
        float2 _n2UV    = fd.uv0; \
        if(_Bump2ndMap_UVMode == 1) _n2UV = fd.uv1; \
        if(_Bump2ndMap_UVMode == 2) _n2UV = fd.uv2; \
        if(_Bump2ndMap_UVMode == 3) _n2UV = fd.uv3; \
        float4 _n2Tex   = LIL_SAMPLE_2D_ST(_Bump2ndMap, lil_sampler_linear_repeat, _n2UV); \
        float  _n2Scale = _Bump2ndScale * LIL_SAMPLE_2D_ST(_Bump2ndScaleMask, sampler_MainTex, fd.uvMain).r; \
        normalmap       = lilBlendNormal(normalmap, lilUnpackNormalScale(_n2Tex, _n2Scale)); \
    }

// BEFORE_MAIN2ND / BEFORE_MAIN3RD - save pre-layer colors for shadow suppress correction
#define BEFORE_MAIN2ND \
    float3 _dnkw_pre2nd = fd.col.rgb;

#define BEFORE_MAIN3RD \
    float3 _dnkw_pre3rd = fd.col.rgb;

// BEFORE_AUDIOLINK - 3rd Normal Map (composited after lilToon's normal pipeline)
// Uses lilUnpackNormalScale + lilBlendNormal, identical to lilToon's 1st->2nd blend,
// so strength scales the tangent xy without clamping (values >1 amplify, matching 1st/2nd)
// and additively layers on top of the existing 1st/2nd result.
// fd.reflectionN/matcapN/matcap2ndN/uvMat are updated here because they were set
// from the pre-3rd fd.N earlier in the pipeline (lil_pass_forward_normal.hlsl:314-316).
#define BEFORE_AUDIOLINK \
    if (_CustomNormal3rdEnabled > 0.5) { \
        float2 _n3UV    = fd.uv0 * _CustomNormal3rdTex_ST.xy + _CustomNormal3rdTex_ST.zw; \
        float  _n3Mask  = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, fd.uv0).b; \
        float4 _n3Raw   = LIL_SAMPLE_2D(_CustomNormal3rdTex, sampler_linear_repeat, _n3UV); \
        float3 _n3NTS   = lilUnpackNormalScale(_n3Raw, _CustomNormal3rdStrength * _n3Mask); \
        float3 _nCurTS  = mul(fd.TBN, fd.N); \
        float3 _nBlend  = lilBlendNormal(_nCurTS, _n3NTS); \
        fd.N            = normalize(mul(_nBlend, fd.TBN)); \
        fd.reflectionN  = fd.N; \
        fd.matcapN      = fd.N; \
        fd.matcap2ndN   = fd.N; \
        fd.uvMat        = mul(fd.cameraMatrix, fd.N).xy * 0.5 + 0.5; \
    }

// BEFORE_REFLECTION - 2nd Reflection
// Isotropic (VRCLV): LightVolumeSpecular with LV color intensity control.
//   _CustomRefl2ndLVColorStrength: 0=LV輝度のみ(色無し), 1=LV色をフルで受け取る(デフォルト)
// Anisotropic: Kajiya-Kay (fd.L / fd.lightColor)
// 両パス共通: _CustomRefl2ndMainColorStrength でfd.albedoを最終出力に乗算
#if DNKW_VRCLV_AVAILABLE
#define BEFORE_REFLECTION \
    if (_CustomRefl2ndEnabled > 0.5) { \
        float2 _r2MaskUV = fd.uv0 * _CustomRefl2ndMaskTex_ST.xy + _CustomRefl2ndMaskTex_ST.zw; \
        float  _r2Mask   = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, _r2MaskUV).r; \
        float  _r2Shadow = lerp(1.0, fd.shadowmix, _CustomRefl2ndShadowAttenuation); \
        float3 _r2Out; \
        if (_CustomRefl2ndAnisotropic > 0.5) { \
            float  _r2Shininess = exp2(_CustomRefl2ndSmoothness * 10.0 + 1.0); \
            float3 _r2H  = normalize(fd.L + fd.V); \
            float3 _r2T1 = normalize(fd.TBN[1] + fd.N * _CustomRefl2ndAnisoPrimaryShift); \
            float  _r2TH1   = dot(_r2T1, _r2H); \
            float  _r2Spec1 = smoothstep(-1.0, 0.0, _r2TH1) * pow(sqrt(max(0.0, 1.0 - _r2TH1 * _r2TH1)), _r2Shininess); \
            float3 _r2T2 = normalize(fd.TBN[1] + fd.N * _CustomRefl2ndAnisoSecondaryShift); \
            float  _r2TH2   = dot(_r2T2, _r2H); \
            float  _r2Spec2 = smoothstep(-1.0, 0.0, _r2TH2) * pow(sqrt(max(0.0, 1.0 - _r2TH2 * _r2TH2)), _r2Shininess * 0.5); \
            _r2Spec1 = lerp(step(0.5, _r2Spec1), _r2Spec1, _CustomRefl2ndBlur); \
            _r2Spec2 = lerp(step(0.5, _r2Spec2), _r2Spec2, _CustomRefl2ndBlur); \
            _r2Out = (_CustomRefl2ndColor.rgb * _r2Spec1 + _CustomRefl2ndAnisoSecondaryColor.rgb * _r2Spec2 * _CustomRefl2ndAnisoSecondaryStrength) * _CustomRefl2ndStrength * _r2Mask * _r2Shadow * fd.lightColor; \
        } else { \
            float3 _r2L0, _r2L1r, _r2L1g, _r2L1b; \
            LightVolumeSH(fd.positionWS, _r2L0, _r2L1r, _r2L1g, _r2L1b); \
            float3 _r2Spec = LightVolumeSpecular(float3(1.0, 1.0, 1.0), _CustomRefl2ndSmoothness, 1.0, fd.N, fd.V, _r2L0, _r2L1r, _r2L1g, _r2L1b); \
            float  _r2Lum  = dot(_r2Spec, float3(0.299, 0.587, 0.114)); \
            _r2Spec = lerp(float3(_r2Lum, _r2Lum, _r2Lum), _r2Spec, _CustomRefl2ndLVColorStrength); \
            float  _r2PostLum = dot(_r2Spec, float3(0.299, 0.587, 0.114)); \
            float  _r2Shaped  = lerp(step(0.5, _r2PostLum), _r2PostLum, _CustomRefl2ndBlur); \
            _r2Spec *= _r2Shaped / max(_r2PostLum, 1e-5); \
            _r2Out  = _r2Spec * _CustomRefl2ndColor.rgb * _CustomRefl2ndStrength * _r2Mask; \
        } \
        fd.col.rgb += _r2Out * lerp(float3(1.0, 1.0, 1.0), fd.albedo, _CustomRefl2ndMainColorStrength); \
    }
#else
#define BEFORE_REFLECTION \
    if (_CustomRefl2ndEnabled > 0.5) { \
        float2 _r2MaskUV    = fd.uv0 * _CustomRefl2ndMaskTex_ST.xy + _CustomRefl2ndMaskTex_ST.zw; \
        float  _r2Mask      = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, _r2MaskUV).r; \
        float  _r2Shininess = exp2(_CustomRefl2ndSmoothness * 10.0 + 1.0); \
        float  _r2Shadow    = lerp(1.0, fd.shadowmix, _CustomRefl2ndShadowAttenuation); \
        float3 _r2H         = normalize(fd.L + fd.V); \
        float3 _r2Out; \
        if (_CustomRefl2ndAnisotropic > 0.5) { \
            float3 _r2T1    = normalize(fd.TBN[1] + fd.N * _CustomRefl2ndAnisoPrimaryShift); \
            float  _r2TH1   = dot(_r2T1, _r2H); \
            float  _r2Spec1 = smoothstep(-1.0, 0.0, _r2TH1) * pow(sqrt(max(0.0, 1.0 - _r2TH1 * _r2TH1)), _r2Shininess); \
            float3 _r2T2    = normalize(fd.TBN[1] + fd.N * _CustomRefl2ndAnisoSecondaryShift); \
            float  _r2TH2   = dot(_r2T2, _r2H); \
            float  _r2Spec2 = smoothstep(-1.0, 0.0, _r2TH2) * pow(sqrt(max(0.0, 1.0 - _r2TH2 * _r2TH2)), _r2Shininess * 0.5); \
            _r2Spec1 = lerp(step(0.5, _r2Spec1), _r2Spec1, _CustomRefl2ndBlur); \
            _r2Spec2 = lerp(step(0.5, _r2Spec2), _r2Spec2, _CustomRefl2ndBlur); \
            _r2Out = (_CustomRefl2ndColor.rgb * _r2Spec1 + _CustomRefl2ndAnisoSecondaryColor.rgb * _r2Spec2 * _CustomRefl2ndAnisoSecondaryStrength) * _CustomRefl2ndStrength * _r2Mask * _r2Shadow * fd.lightColor; \
        } else { \
            float  _r2NdotH = saturate(dot(fd.N, _r2H)); \
            float  _r2Spec  = pow(_r2NdotH, _r2Shininess); \
            _r2Spec = lerp(step(0.5, _r2Spec), _r2Spec, _CustomRefl2ndBlur); \
            _r2Out = _CustomRefl2ndColor.rgb * _r2Spec * _CustomRefl2ndStrength * _r2Mask * _r2Shadow * fd.lightColor; \
        } \
        fd.col.rgb += _r2Out * lerp(float3(1.0, 1.0, 1.0), fd.albedo, _CustomRefl2ndMainColorStrength); \
    }
#endif

// BEFORE_MATCAP - Main 2nd/3rd shadow suppress + Decal UV setup + Decal base map
//
// Shadow suppress: at this hook fd.shadowmix is available and fd.albedo is the full
// pre-lighting unlit color. _dnkw_pre2nd/_dnkw_pre3rd were captured at BEFORE_MAIN2ND/3RD.
// The correction removes the proportional lit contribution of each layer in shadow areas.
//
// Decal UV: same algorithm as lilCalcDecalUV.
//   Position (PosX/PosY) = decal center in UV space (0.5,0.5 = mesh UV center).
//   Size (SizeX/SizeY)   = fraction of UV space covered (1.0 = full UV width/height).
//   Tiling = 1/Size,  Offset = 0.5 - Pos * Tiling
//   Rotation is around mesh UV center (0.5,0.5), same as lilRotateUV.
//
// _CustomDecalMaskTex is sampled in DECAL UV SPACE (same transform as the decal texture).
//   This means the mask scales, moves, and rotates together with the decal.
//   It controls the precise shape of the effect within the placed decal area.
//   _dnkw_decalMask (bounds * maskTex.r) is stored for reuse in BEFORE_RIMLIGHT (Matcap).
//
// BlendMode: 0=Replace, 1=Add, 2=Screen, 3=Multiply.
#define BEFORE_MATCAP \
    { \
        float  _mc_sinv  = 1.0 - fd.shadowmix; \
        float3 _mc_ratio = fd.col.rgb / max(fd.albedo, float3(0.001, 0.001, 0.001)); \
        if (_CustomMain2ndShadowDisable > 0.001) { \
            float3 _mc_d2 = _dnkw_pre3rd - _dnkw_pre2nd; \
            fd.col.rgb -= saturate(_mc_d2) * _mc_ratio * (_mc_sinv * _CustomMain2ndShadowDisable); \
        } \
        if (_CustomMain3rdShadowDisable > 0.001) { \
            float3 _mc_d3 = fd.albedo - _dnkw_pre3rd; \
            fd.col.rgb -= saturate(_mc_d3) * _mc_ratio * (_mc_sinv * _CustomMain3rdShadowDisable); \
        } \
        fd.col.rgb = max(fd.col.rgb, 0.0); \
    } \
    /* Compute decal UV once; result shared with BEFORE_RIMLIGHT via _dnkw_decalMask. */ \
    float _dnkw_decalMask = 0.0; \
    float2 _dnkw_decalUV  = float2(0.0, 0.0); \
    float2 _dnkw_decalDdx = float2(0.0, 0.0); \
    float2 _dnkw_decalDdy = float2(0.0, 0.0); \
    if (_CustomDecalEnabled > 0.5 || _CustomDecalMatcapEnabled > 0.5) { \
        float2 _dTiling = float2(1.0 / max(_CustomDecalSizeX, 0.0001), \
                                 1.0 / max(_CustomDecalSizeY, 0.0001)); \
        float2 _dOffset = 0.5 - float2(_CustomDecalPosX, _CustomDecalPosY) * _dTiling; \
        float  _dAngle  = _CustomDecalAngle * 0.01745329252; \
        float  _dSin, _dCos; \
        sincos(_dAngle, _dSin, _dCos); \
        float2 _dC = fd.uv0 - 0.5; \
        float2 _dRotUV = float2(_dC.x * _dCos - _dC.y * _dSin + 0.5, \
                                _dC.x * _dSin + _dC.y * _dCos + 0.5); \
        _dnkw_decalUV  = _dRotUV * _dTiling + _dOffset; \
        /* Weaken the tiling-magnified mip response so the decal stays sharp. */ \
        _dnkw_decalDdx = ddx(_dnkw_decalUV) * DNKW_DECAL_MIP_GRAD_SCALE; \
        _dnkw_decalDdy = ddy(_dnkw_decalUV) * DNKW_DECAL_MIP_GRAD_SCALE; \
        float  _dInBounds = step(0.0, _dnkw_decalUV.x) * step(_dnkw_decalUV.x, 1.0) \
                          * step(0.0, _dnkw_decalUV.y) * step(_dnkw_decalUV.y, 1.0); \
        /* Mask sampled in decal UV space → scales/moves/rotates with the decal. */ \
        float  _dMaskTex  = LIL_SAMPLE_2D_GRAD(_CustomDecalMaskTex, sampler_linear_repeat, _dnkw_decalUV, _dnkw_decalDdx, _dnkw_decalDdy).r; \
        _dnkw_decalMask   = _dInBounds * _dMaskTex; \
    } \
    if (_CustomDecalEnabled > 0.5) { \
        float4 _dTex    = LIL_SAMPLE_2D_GRAD(_CustomDecalTex, sampler_linear_repeat, _dnkw_decalUV, _dnkw_decalDdx, _dnkw_decalDdy); \
        float  _dShadow = lerp(1.0, fd.shadowmix, _CustomDecalShadowDisable); \
        float  _dAlpha  = _dTex.a * _CustomDecalAlpha * _dnkw_decalMask * _dShadow; \
        float3 _dColor  = _dTex.rgb * _CustomDecalColor.rgb; \
        fd.col.rgb = DNKW_DecalBlend(fd.col.rgb, _dColor, _dAlpha, _CustomDecalBlendMode); \
    }

// BEFORE_RIMLIGHT - Decal Matcap
// Matcap UV is view-space; the placement mask is _dnkw_decalMask computed in BEFORE_MATCAP.
// Both base and matcap share the same positioned/scaled/rotated decal mask.
#define BEFORE_RIMLIGHT \
    if (_CustomDecalMatcapEnabled > 0.5) { \
        float3 _mcNVS    = mul((float3x3)UNITY_MATRIX_V, fd.N); \
        float2 _mcUV     = _mcNVS.xy * 0.5 + 0.5; \
        float4 _mcTex    = LIL_SAMPLE_2D(_CustomDecalMatcapTex, sampler_linear_repeat, _mcUV); \
        float  _mcShadow = lerp(1.0, fd.shadowmix, _CustomDecalMatcapShadowDisable); \
        float3 _mcColor  = _mcTex.rgb * _CustomDecalMatcapColor.rgb; \
        float  _mcAlpha  = _mcTex.a * _CustomDecalMatcapAlpha * _dnkw_decalMask * _mcShadow; \
        fd.col.rgb = DNKW_DecalBlend(fd.col.rgb, _mcColor, _mcAlpha, _CustomDecalMatcapBlendMode); \
    }

// BEFORE_EMISSION_1ST - 2nd Rim (Applied after standard rim light processing)
// BlendMode: 0=RimLight(Add) / 1=RimShade(Multiply)
#define BEFORE_EMISSION_1ST \
    if (_CustomRim2ndEnabled > 0.5) { \
        float  _rim2Mask   = LIL_SAMPLE_2D(_CustomMaskPacked, sampler_linear_repeat, fd.uv0).g; \
        float  _rim2NdotV  = saturate(dot(fd.N, fd.V)); \
        float  _rim2Val    = pow(1.0 - _rim2NdotV, _CustomRim2ndPower); \
        _rim2Val = lerp(step(0.5, _rim2Val), _rim2Val, _CustomRim2ndBlur); \
        float  _rim2Shadow = lerp(1.0, fd.shadowmix, _CustomRim2ndShadowAttenuation); \
        float  _rim2Amt    = _rim2Val * _CustomRim2ndStrength * _rim2Mask * _rim2Shadow; \
        float3 _rim2Color  = _CustomRim2ndColor.rgb * lerp(float3(1.0, 1.0, 1.0), fd.albedo, _CustomRim2ndMainColorStrength); \
        if (_CustomRim2ndBlendMode < 0.5) { \
            fd.col.rgb += _rim2Color * _rim2Amt; \
        } else { \
            fd.col.rgb = lerp(fd.col.rgb, fd.col.rgb * _rim2Color, _rim2Amt); \
        } \
    }

//----------------------------------------------------------------------------------------------------------------------
// Information about variables
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// Vertex shader inputs (appdata structure)
//
// Type     Name                    Description
// -------- ----------------------- --------------------------------------------------------------------
// float4   input.positionOS        POSITION
// float2   input.uv0               TEXCOORD0
// float2   input.uv1               TEXCOORD1
// float2   input.uv2               TEXCOORD2
// float2   input.uv3               TEXCOORD3
// float2   input.uv4               TEXCOORD4
// float2   input.uv5               TEXCOORD5
// float2   input.uv6               TEXCOORD6
// float2   input.uv7               TEXCOORD7
// float4   input.color             COLOR
// float3   input.normalOS          NORMAL
// float4   input.tangentOS         TANGENT
// uint     vertexID                SV_VertexID

//----------------------------------------------------------------------------------------------------------------------
// Vertex shader outputs or pixel shader inputs (v2f structure)
//
// The structure depends on the pass.
// Please check lil_pass_xx.hlsl for details.
//
// Type     Name                    Description
// -------- ----------------------- --------------------------------------------------------------------
// float4   output.positionCS       SV_POSITION
// float2   output.uv01             TEXCOORD0 TEXCOORD1
// float2   output.uv23             TEXCOORD2 TEXCOORD3
// float3   output.positionOS       object space position
// float3   output.positionWS       world space position
// float3   output.normalWS         world space normal
// float4   output.tangentWS        world space tangent

//----------------------------------------------------------------------------------------------------------------------
// Variables commonly used in the forward pass
//
// These are members of `lilFragData fd`
//
// Type     Name                    Description
// -------- ----------------------- --------------------------------------------------------------------
// float4   col                     lit color
// float3   albedo                  unlit color
// float3   emissionColor           color of emission
// -------- ----------------------- --------------------------------------------------------------------
// float3   lightColor              color of light
// float3   indLightColor           color of indirectional light
// float3   addLightColor           color of additional light
// float    attenuation             attenuation of light
// float3   invLighting             saturate((1.0 - lightColor) * sqrt(lightColor));
// -------- ----------------------- --------------------------------------------------------------------
// float2   uv0                     TEXCOORD0
// float2   uv1                     TEXCOORD1
// float2   uv2                     TEXCOORD2
// float2   uv3                     TEXCOORD3
// float2   uvMain                  Main UV
// float2   uvMat                   MatCap UV
// float2   uvRim                   Rim Light UV
// float2   uvPanorama              Panorama UV
// float2   uvScn                   Screen UV
// bool     isRightHand             input.tangentWS.w > 0.0;
// -------- ----------------------- --------------------------------------------------------------------
// float3   positionOS              object space position
// float3   positionWS              world space position
// float4   positionCS              clip space position
// float4   positionSS              screen space position
// float    depth                   distance from camera
// -------- ----------------------- --------------------------------------------------------------------
// float3x3 TBN                     tangent / bitangent / normal matrix
// float3   T                       tangent direction
// float3   B                       bitangent direction
// float3   N                       normal direction
// float3   V                       view direction
// float3   L                       light direction
// float3   origN                   normal direction without normal map
// float3   origL                   light direction without sh light
// float3   headV                   middle view direction of 2 cameras
// float3   reflectionN             normal direction for reflection
// float3   matcapN                 normal direction for reflection for MatCap
// float3   matcap2ndN              normal direction for reflection for MatCap 2nd
// float    facing                  VFACE
// -------- ----------------------- --------------------------------------------------------------------
// float    vl                      dot(viewDirection, lightDirection);
// float    hl                      dot(headDirection, lightDirection);
// float    ln                      dot(lightDirection, normalDirection);
// float    nv                      saturate(dot(normalDirection, viewDirection));
// float    nvabs                   abs(dot(normalDirection, viewDirection));
// -------- ----------------------- --------------------------------------------------------------------
// float4   triMask                 TriMask (for lite version)
// float3   parallaxViewDirection   mul(tbnWS, viewDirection);
// float2   parallaxOffset          parallaxViewDirection.xy / (parallaxViewDirection.z+0.5);
// float    anisotropy              strength of anisotropy
// float    smoothness              smoothness
// float    roughness               roughness
// float    perceptualRoughness     perceptual roughness
// float    shadowmix               this variable is 0 in the shadow area
// float    audioLinkValue          volume acquired by AudioLink
// -------- ----------------------- --------------------------------------------------------------------
// uint     renderingLayers         light layer of object (for URP / HDRP)
// uint     featureFlags            feature flags (for HDRP)
// uint2    tileIndex               tile index (for HDRP)
