// DennokoEx VRCLV Bridge
// This file is always shipped unchanged. VRCLV activation is delegated to
// DennokoEx_VRCLV_Inject.cginc (auto-generated by DennokoExVRCLVDetector.cs).
// Do NOT modify this file manually.
#ifndef DNKW_VRCLV_BRIDGE_INCLUDED
#define DNKW_VRCLV_BRIDGE_INCLUDED

// Inject file: empty when VRCLV is absent, includes LightVolumes.cginc when present.
#include "DennokoEx_VRCLV_Inject.cginc~"

#ifdef DNKW_VRCLV_INJECTED
    #define DNKW_VRCLV_AVAILABLE 1
#else
    #define DNKW_VRCLV_AVAILABLE 0
#endif

#endif
