// Auto-generated by DennokoExVRCLVDetector.cs — do not edit manually.
// To regenerate: Window > DennokoEx > Regenerate VRCLV Bridge
#ifndef DNKW_VRCLV_BRIDGE_INCLUDED
#define DNKW_VRCLV_BRIDGE_INCLUDED
#define DNKW_VRCLV_AVAILABLE 0
#endif
